# Generated by Django 4.1.2 on 2023-10-29 11:49

import uuid
from django.db import migrations


def generate_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.username = uuid.uuid4()
        row.save(update_fields=["username"])


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_add_field_username_nullable_to_user"),
    ]

    operations = [
        migrations.RunPython(generate_uuid),
    ]
