# Generated by Django 4.1.2 on 2023-11-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_username_set_default_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(
                default="!GHkPTL0F51FypiP2wwjrNTQ0YcvfkyuLLkucQ1bZ", max_length=128
            ),
        ),
    ]
