# Generated by Django 4.1.2 on 2023-12-07 08:18

import django.contrib.auth.validators
from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_change_default_is_active_to_false"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                default=users.utils.generate_random_username,
                max_length=55,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
            ),
        ),
    ]
