version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: ./docker-entrypoint.sh
    ports:
      - 80:8000
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      - ALLOWED_HOST=${ALLOWED_HOST}
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.1
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
