FROM python:3.9.15

RUN pip install --upgrade pip

WORKDIR /app

COPY /requirements/common.txt /requirements/prod.txt /requirements/

RUN pip install --no-cache-dir -r /requirements/prod.txt \
    && adduser --disabled-password --no-create-home appuser \
    && mkdir -p /static /media \
    && chown -R appuser /static /media \
    && chmod -R 755 /static /media

COPY . /app

USER appuser
