version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./docker-entrypoint.dev.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=scribbly
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio
    command: server /data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    volumes:
      - minio-data:/data
    restart: always

volumes:
  postgres-data:
  redis-data:
