version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./api-docker-entrypoint.dev.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=scribbly
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./celery-docker-entrypoint.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.12.14-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=password
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - 15672:15672 # RabbitMQ management interface

volumes:
  postgres-data:
  redis-data:
  rabbitmq-data:
