FROM python:3.9.15

RUN pip install --upgrade pip

WORKDIR /app

COPY /requirements/common.txt /requirements/prod.txt /requirements/
RUN pip install --no-cache-dir -r /requirements/prod.txt

COPY . /app

RUN groupadd -r appuser && \
    useradd -r -g appuser appuser && \
    chmod +x /app/docker-entrypoint.prod.sh /app/wait-for-it.sh && \
    chown -R appuser:appuser /app

USER appuser
