version: "3.9"

services:
  api:
    build: .
    command: ./docker-entrypoint.sh
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:16.1
    environment:
      - POSTGRES_DB=scribbly
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
