# Generated by Django 4.1.2 on 2024-03-31 12:51

import chat.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(
                default=chat.utils.generate_random_room_name, max_length=55
            ),
        ),
    ]
