# Generated by Django 4.1.2 on 2023-12-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="chat",
        ),
        migrations.AddField(
            model_name="message",
            name="chats",
            field=models.ManyToManyField(related_name="messages", to="chat.chat"),
        ),
    ]
