# Generated by Django 4.1.2 on 2024-04-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_rename_chat_to_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=55),
        ),
    ]
