# Generated by Django 4.1.2 on 2023-12-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_chats_to_rooms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
