# Generated by Django 4.1.2 on 2024-04-10 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_rename_user_to_sender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="name",
        ),
    ]
