# Generated by Django 4.1.2 on 2023-12-20 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0005_remove_default_from_name_field_in_room"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="room",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(max_length=55),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("name", "user", "partner")},
        ),
    ]
