# Generated by Django 4.1.2 on 2024-04-14 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_remove_room_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="room",
            old_name="participant",
            new_name="contact",
        ),
    ]
