# Generated by Django 4.1.2 on 2023-12-26 13:22

import chat.utils
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_add_name_field_to_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="name",
            field=models.CharField(
                default=chat.utils.generate_random_room_name, max_length=55
            ),
        ),
    ]
