# Generated by Django 4.1.2 on 2024-04-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_rename_participant_to_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
