# Generated by Django 4.1.2 on 2023-10-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("heading", models.CharField(blank=True, max_length=255, null=True)),
                ("summary", models.CharField(blank=True, max_length=255, null=True)),
                ("label", models.CharField(blank=True, max_length=55, null=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="blog.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
