# Generated by Django 4.1.2 on 2023-10-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_rename_field_url_on_articleimage_to_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="childs",
                to="blog.category",
            ),
        ),
    ]
