# Generated by Django 4.1.2 on 2023-10-25 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_create_articlelike"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="articleimage",
            name="updated_at",
        ),
    ]
