# Generated by Django 4.1.2 on 2023-10-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_remove_field_updated_at_from_articleimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="likes_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
