# Generated by Django 4.1.2 on 2023-10-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0009_add_field_likes_count_to_article"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="articlelike",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="articlelike",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="blog.author",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="articlelike",
            unique_together={("article", "author")},
        ),
        migrations.RemoveField(
            model_name="articlelike",
            name="user",
        ),
    ]
