# Generated by Django 4.1.2 on 2023-10-26 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0011_create_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="comments_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
