# Generated by Django 4.1.2 on 2023-10-28 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0013_rename_field_reply_to_on_comment_to_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="comments_count",
        ),
        migrations.RemoveField(
            model_name="article",
            name="likes_count",
        ),
    ]
