# Generated by Django 4.1.2 on 2023-10-28 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0014_remove_fields_likes_counts_and_comments_count_from_article"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reply_to_author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.author"
            ),
        ),
    ]
