# Generated by Django 4.1.2 on 2023-10-28 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0015_add_field_reply_to_author_to_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="reply_to_author",
            new_name="reply_to",
        ),
    ]
