apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
    - host: api.djosers.ir
      http:
        paths:
          - backend:
              serviceName: api-service
              servicePort: 8000
