apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mihrdatmahmoodpoor/scribbly:1.0.0
          command: ./docker-entrypoint.prod.sh
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api
                  key: secretkey
            - name: DATABASE_URL
              value: postgres://postgres:<password>@postgres-service/scribbly
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.prod
            - name: ALLOWED_HOSTS
              value: 51.107.8.211|api.djosers.ir
          ports:
            - containerPort: 8000
