apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: api.djosers.ir
      http:
        paths:
          - path: /
            backend:
              serviceName: api-service
              servicePort: 8000
