apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: mihrdatmahmoodpoor/scribbly:1.0.4
          command: ["./docker-entrypoint.prod.sh"]
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: api-credentials
                  key: database-url
            - name: DJANGO_SETTINGS_MODULE
              value: config.settings.prod
            - name: ALLOWED_HOSTS
              value: "api.djosers.ir"
          ports:
            - containerPort: 8000
