secretGenerator:
  - name: api-credentials
    literals:
      - secret-key=supersecretkeyhere
      - database-url=postgres://postgres:supersecretpasswordhere@postgres:5432/scribbly
  - name: db-credentials
    literals:
      - password=supersecretpasswordhere
resources:
  - postgres-deployment.yml
  - postgres-service.yml
  - api-deployment.yml
  - api-service.yml
