secretGenerator:
  - name: api-credentials
    literals:
      - secret-key=$(SECRET_KEY)
      - database-url=$(DATABASE_URL)
  - name: db-credentials
    literals:
      - password=$(DB_PASSWORD)
resources:
  - postgres-deployment.yml
  - postgres-service.yml
  - api-deployment.yml
  - api-service.yml
