apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  claimRef:
    namespace: default
    name: postgres-pvc
  hostPath:
    path: /mnt/data/postgres
    type: DirectoryOrCreate
